name: Package Persepolis DM for macos intel
on: workflow_dispatch
jobs:
  bundle-macos:
    runs-on: macos-latest
    steps:

      - name: Get build assets
        uses: actions/checkout@v4
        with:
          repository: persepolisdm/mac-package-build
          path: mac-package-build
      - name: Install requirements
        run: pip install PySide6 requests yt_dlp pyinstaller urllib3 pysocks
      - name: Install wiwt Brew
        run: brew install wget create-dmg unzip
      - name: Download ffmpeg
        run: wget --trust-server-names https://evermeet.cx/ffmpeg/getrelease/ffmpeg/zip -O ffmpeg.zip && unzip -o ffmpeg.zip && rm ffmpeg.zip
      - name: Build
        run: |
          cd mac-package-build
          git clone https://github.com/persepolisdm/persepolis.git
          find persepolis/persepolis -type f -exec perl -i -pe 's/persepolis.scripts/scripts/g' '{}' \;
          find persepolis/persepolis -type f -exec perl -i -pe 's/persepolis.gui/gui/g' '{}' \;
          pyinstaller app.spec
