name: bundle Persepolis Download Manager for windosw
on: workflow_dispatch
jobs:
  bundle-windows:
    runs-on: windows-latest
    steps:
      - name: Get persepolis
        uses: actions/checkout@v4
        with:
          repository: persepolisdm/persepolis
          path: persepolis
      - name: Get build assets
        uses: actions/checkout@v4
        with:
          repository: persepolisdm/persepolis-windows-package-build
          path: persepolis-windows-package-build
      #- name: Install requirements
     #   run: pip install PySide6 requests pypiwin32 setproctitle psutil yt_dlp pyinstaller urllib3
      - name: Download ffmpeg
        uses: robinraju/release-downloader@v1.10
        with:
          repository: "yt-dlp/FFmpeg-Builds"
          latest: true
          fileName: "ffmpeg-master-latest-win64-gpl.zip"
      #- name: Build
      #  run: |
      #    cd persepolis
      #    pyinstaller '.\resources\PersepolisBI.py' -F -i '..\persepolis-windows-package-build\persepolis2.ico' -n "PersepolisBI" --version-file '..\persepolis-windows-package-build\bi_version.py' --clean
      #    pyinstaller '.\persepolis\Persepolis Download Manager.py' -F -w -i '..\persepolis-windows-package-build\persepolis1.ico' -n "Persepolis Download Manager" --version-file '..\persepolis-windows-package-build\version.py' --clean
      - name: Extract ffmpeg
        run: 7z x ffmpeg-master-latest-win64-gpl.zip -o'.\persepolis\dist'
      - name: list
        run: |
          dir
          cd persepolis\dist
          dir
